[[server]]
id = 768208778780475447
gamba.points_name = "nuggies"

[server.roles]
no_pings = [768232863043682314, 768233366889300028]

[server.cooldown]
default_seconds = 15
exempt = [903465905630089236]

[server.automod]
log_channel = 790632143037399070
text_prefix = "<@&768232863043682314> Problematic message detected. Please select an appropriate action below."

[server.commands]
corgi.enabled = true
roles.enabled = false
waffle.enabled = true
